@HOST = http://localhost:3000/vin/sap

### List logs
GET {{HOST}}/logs

### List order
GET {{HOST}}/orders

### List order
DELETE {{HOST}}/orders

### List sale orders
GET {{HOST}}/saleorders

### Get order

GET {{HOST}}/orders/O_100001

### Create order
POST {{HOST}}/saleorders
Content-Type: application/json

{
  "OrderInfo": {
    "voucherValue": 0,
    "deliveryBlock": "",
    "OrderStatus": "",
    "fulfillment": "",
    "SalesOrganization": "",
    "OrderDateUTC": "",
    "PaymentStatus": "",
    "SalesOffice": "",
    "deliveryNote": "",
    "voucherCode": "",
    "OrderItems": [
      {
        "OrderItemId": "",
        "OrderId": "",
        "ProductCode": "",
        "Gtin": "",
        "UnitPrice": 0,
        "DiscountPrice": 0,
        "Quantity": 0,
        "SaleUoM": "",
        "Plant": "",
        "unitPrice": "",
        "category": "",
        "offerId": ""
      }
    ],
    "OrderTotal": 0,
    "OriginalOrderId": "",
    "eShipment": "",
    "eOrder": "",
    "DistributionChannel": "",
    "Division": "",
    "SalesType": "",
    "OrderId": "O_100002",
    "conditions": [
      {
        "itemNo": "",
        "type": "",
        "value": "",
        "currency": ""
      }
    ],
    "OrderTotalDiscount": 0,
    "paymentTerm": "",
    "ShippingAddressInfo": {
      "CustomerFirstName": "",
      "CustomerLastName": "",
      "CustomerEmail": "",
      "Company": "",
      "Country": "",
      "StateProvince": "",
      "StateProvinceName": "",
      "City": "",
      "CityCode": "",
      "Ward": "",
      "WardCode": "",
      "Address1": "",
      "Address2": "",
      "PhoneNumber": ""
    },
    "CustomerInfo": {
      "CustomerNumber": "",
      "Username": "",
      "Email": "",
      "TaxCode": "",
      "Level": "",
      "Mobile": "",
      "Title": "",
      "FirstName": "",
      "LastName": "",
      "BirthDate": ""
    }
  }
}